- docs/AboutUs.md
> Update Joel readme

- docs/AboutUs.md
Pull Request from Jonathan-AboutUs to update team repo master branch
> Jonathan-About Us

- src/main/java/seedu/duke/CommandParser.java
- src/main/java/seedu/duke/Duke.java
- src/main/java/seedu/duke/Specialisation.java
> Add CommandParser class and detects input

- src/main/java/seedu/duke/CommandParser.java
- src/main/java/seedu/duke/Duke.java
- src/main/java/seedu/duke/Specialisation.java
> Add /specialisation to view all specialisations

- src/main/java/seedu/duke/CommandParser.java
> Fix specialisation command

- src/main/java/seedu/duke/Specialisation.java
Fix specialisation line spacing
> Fix specialisation line spacing

- src/main/java/seedu/duke/Duke.java
Add try catch to commandparser
> Add try catch to commandparser

- build.gradle
- src/main/java/seedu/duke/Duke.java
- src/main/java/seedu/duke/command/AddModule.java
- src/main/java/seedu/duke/command/Command.java
- src/main/java/seedu/duke/command/DeleteModule.java
- src/main/java/seedu/duke/command/ListModules.java
- src/main/java/seedu/duke/data/Mod.java
- src/main/java/seedu/duke/data/Module.java
Created Mod class too to represent modules
AddModule function to be integrated with a function that finds the module through the database using module code (modCode)  to create the Mod object to be added to the list
> Implement Add, Delete, List Module Functions

- src/main/java/seedu/duke/CommandParser.java
- src/main/java/seedu/duke/command/SuUserModule.java
- src/main/java/seedu/duke/data/User.java
> added SU fucntionality - command = /su

- src/main/java/seedu/duke/CommandParser.java
- src/main/java/seedu/duke/command/AddUserModule.java
- src/main/java/seedu/duke/command/DeleteUserModule.java
- src/test/java/seedu/duke/CommandParserTest.java
Fix duplicated print statements
> Fix duplicated print statements

- src/main/java/seedu/duke/CommandParser.java
- src/main/java/seedu/duke/command/DetailModules.java
- src/main/java/seedu/duke/command/ListModules.java
- src/main/java/seedu/duke/data/GradModuleList.java
- src/main/java/seedu/duke/data/Grade.java
- src/main/java/seedu/duke/data/MasterModuleList.java
- src/main/java/seedu/duke/data/Mod.java
- src/main/java/seedu/duke/data/Prereq.java
- src/main/java/seedu/duke/data/User.java
- src/main/java/seedu/duke/data/UserMod.java
- src/main/java/seedu/duke/errors/ModNotInDatabase.java
- src/test/java/seedu/duke/CommandParserTest.java
- src/test/java/seedu/duke/command/AddUserModuleTest.java
Edited add function too to stop invalid modules
Result of adding invalid user is error message telling user to use /addCustom function instead, need to change this if not implementing
> Check prereq

- docs/DeveloperGuide.md
- src/main/java/seedu/duke/CommandParser.java
> DG manual testing

- src/main/java/seedu/duke/CommandParser.java
- src/main/java/seedu/duke/Duke.java
- src/main/java/seedu/duke/command/Help.java
- src/main/java/seedu/duke/command/Specialisation.java
Make all commands implement Command interface
Change logic flow to all create new command only, then any command created is executed at the end of the function
Flip boolean for isRunning
> Unify commands

- docs/DeveloperGuide.md
design: User, UserMod, and Mod classes
implementation: UserGPA and Help
> add implementation and design info to devguide

- docs/team/itsjoelha.md
Added summary of contributions for PPP.
> Update Joel's PPP

- docs/team/itsjoelha.md
Update Joel PPP with contributions
> Update Joel PPP

- docs/team/itsjoelha.md
> Fix Joel PPP

- docs/team/clj55.md
- docs/team/itsjoelha.md
- docs/team/jonathan2745.md
- docs/team/thezerohour.md
- docs/team/xmtan1.md
> Fix gradle

- src/main/java/seedu/duke/command/Specialisation.java
> Format specialisation table

- data/user.txt
- src/main/java/seedu/duke/command/Help.java
> Format /help table

- src/main/java/seedu/duke/command/ViewGradRequirements.java
> Fix /grad table formatting

- src/main/java/seedu/duke/command/AddCustomModule.java
- src/main/java/seedu/duke/command/AddUserModule.java
- src/main/java/seedu/duke/command/ViewGradRequirements.java
- src/test/java/seedu/duke/CommandParserTest.java
> Fix table formatting of /grad

- src/test/java/seedu/duke/CommandParserTest.java
Fix /spec in CommandParserTest
> Fix /spec in CommandParserTest

- src/main/java/seedu/duke/CommandParser.java
- src/main/java/seedu/duke/command/AddCustomModule.java
- src/main/java/seedu/duke/command/ViewGradRequirements.java
- src/test/java/seedu/duke/CommandParserTest.java
Fix /workload to only allow at most 1 argument
> Fix /workload to only allow at most 1 argument

- src/main/java/seedu/duke/CommandParser.java
- src/test/java/seedu/duke/CommandParserTest.java
Fix /view to only allow at most 1 parameter and must be integer between 1 and 8
> Fix /view to only allow at most 1 parameter and must be integer between 1 and 8

- src/main/java/seedu/duke/command/Help.java
> Fix /help command arguments

- src/main/java/seedu/duke/CommandParser.java
Fix program shutting down with no user input
> Fix program shutting down with no user input

- src/main/java/seedu/duke/CommandParser.java
> fixed addtional arguments bug

- src/main/java/seedu/duke/CommandParser.java
- src/main/java/seedu/duke/command/AddCustomModule.java
- src/main/java/seedu/duke/command/DetailModules.java
- src/main/java/seedu/duke/data/GradModuleList.java
- src/main/java/seedu/duke/data/UserMod.java
- src/test/java/seedu/duke/CommandParserTest.java
Fix argument spacing in Command Parser
> Fix argument spacing in Command Parser

- docs/UserGuide.md
- src/main/java/seedu/duke/command/GradeModule.java
- src/test/java/seedu/duke/CommandParserTest.java
> Add Grade to UG

- src/main/java/seedu/duke/command/ViewGradRequirements.java
- src/main/java/seedu/duke/command/Workload.java
Add JavaDoc Comments for Workload & Grad
> Add JavaDoc Comments for Workload & Grad

- src/main/java/seedu/duke/Ui.java
- src/main/java/seedu/duke/command/AddUserModule.java
- src/main/java/seedu/duke/command/DetailModules.java
Moved print formatting in DetailModules and AddModule to Ui class
> Add Prereq description if missing prereqs after add function

- docs/UserGuide.md
- docs/team/itsjoelha.md
Update UG Command Summary arguments
> Update UG Command Summary arguments

- src/main/java/seedu/duke/Duke.java
- src/main/java/seedu/duke/command/ViewGradRequirements.java
- src/main/java/seedu/duke/storage/UserStorage.java
close #134 #135 #144 #159 and others
> resolve bug with user data file creation

- docs/team/itsjoelha.md
Reverts AY2425S2-CS2113-T11b-2/tp#203
> Revert "Change style & formatting of PPP"

- docs/team/itsjoelha.md
> Update PPP formatting

- docs/diagrams/AddModule.puml
diagram created BUT needs substantial editing
> create AddModule uml diagram

- src/test/java/seedu/duke/command/SpecialisationTest.java
- src/test/java/seedu/duke/storage/UserStorageTest.java
NEED TO FIX THE SPECIALISATION TEST CASE, I COMMENTED OUT AN ASSERTTRUE 
NEED TO FIX USER STORAGE TEST CASE. ALSO COMMENTED OUT
> Fix User Constructor, Commented out testcases

- docs/UserGuide.md
- docs/team/itsjoelha.md
- src/main/java/seedu/duke/CommandParser.java
- src/main/java/seedu/duke/Ui.java
- src/main/java/seedu/duke/command/Help.java
Fix Bugs & update UG for waive command
> Fix Bugs & update UG for waive command

- docs/UserGuide.md
- docs/team/itsjoelha.md
- src/main/java/seedu/duke/command/Help.java
> Update UG with clear
